os: Visual Studio 2017
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set QTDIR=C:\Qt\5.11.1\msvc2017_64
  - set GOPATH=c:\gopath
  - set PATH=%QTDIR%\bin;%GOPATH%\bin;%PATH%
  - go get qpm.io/qpm
  - go install qpm.io/qpm
  - dir %GOPATH%\bin
  - qpm install
  - dir C:\Qt\5.11.1
  - dir C:\Qt\5.11.1\msvc2017_64
  - dir C:\Qt\5.11.1\msvc2017_64\bin
build_script:
  - qmake obsautorecord.pro
  - nmake
