install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - set QTDIR=C:\Qt\5.11.1\msvc2017_64
  - set GOPATH=c:\gopath
  - set PATH=%QTDIR%\bin;%GOPATH%\bin;%PATH%
  - go get qpm.io/qpm
  - go install qpm.io/qpm
  - dir %GOPATH%\bin
  - qpm install
  - dir C:\Qt\5.11.1
  - dir C:\Qt\5.11.1\msvc2017_64
  - dir C:\Qt\5.11.1\msvc2017_64\bin
build_script:
  - C:\Qt\5.11.1\msvc2017_64\bin\qmake.exe obsautorecord.pro
  - nmake
